---
# -------------------------------------------------------
# Repo Clone
# -------------------------------------------------------

- name: Clone Pi-hole Project
  git:
    repo: "{{ project_repo }}"
    dest: "{{ project_dir }}"
    version: testiiing
    force: yes