$ANSIBLE_VAULT;1.1;AES256
62336139373931313535663535306461373838313663643838313032616466363439313066303138
3035643338306564383762626238393638663466663432390a633964343061356362623766356635
64656637386261323233633133383462653738653930313032323736353937333838616663396561
3533613361613764610a336439396132656438306638373866663530663634643866336666303539
39323436666466373338653233353336383663646564383665633132306632646565343764303465
3263633230326365363666333964633463616239363663376330
