$ANSIBLE_VAULT;1.1;AES256
62666234643931383961383061663433653733643564363939363264636163363966643138646561
3936313064373031666661343431373834343138393533350a323566666533646536643639666138
61363337613235393933343937383232633664336630323166356633343934373439643536303966
6237356262323766340a643063643438643562623531303933306366613961643736623633316133
65373632663437373637613536366364313333366634363030633832393637343433
