$ANSIBLE_VAULT;1.1;AES256
35303061363361336134643661666135336635656562626139633962656361646334336239643566
3738323562623063656161386161663066383039326136380a383866613833343031353764353334
36396562373666323838336138626162363562636564373931333437303964363033356333363764
3264366465393630360a323562393065343965373032653366613261356162333364323838386466
62613765376535623439343930616637656337626437343033646466373766623938393033386237
6361636665653562323435346266383032646663663434646336
